### ISSUE TITLE
Add mention of using `.empty` or `.placeholder`

### ISSUE THREAD

**Issue by lindsayplatt** [DOI-USGS/ds-pipelines-targets-1-course#18]
Explain how we want to commit a directory structure, even if files within that folder won't get committed. We often use `.empty` or `.placeholder` text files to do this. This explanation should go in the `Organize your project files` section, and was pointed out by Anthony at https://github.com/amart90/ds-pipelines-targets-1/issues/3#issuecomment-1144051172

Here is an example: https://github.com/USGS-VIZLAB/forecast-drb/tree/main/1_fetch/out

![image](https://user-images.githubusercontent.com/13220910/171633324-bc0cc7b3-e17d-4136-91f9-acc4d5881437.png)

**Comment by padilla410** [comment]
Line 105-107 

https://github.com/USGS-R/ds-pipelines-targets-1-course/pull/19#discussion_r1152758879
